### PR TITLE
Platform independant diff calc

### PR DESCRIPTION
**Pull request by aztech-dev**
As discussed in #12 

(don't merge it yet, I'll rebase once your big refactoring is in)

### CODE REVIEW

**Comment by aztech-dev** [comment]
Allright :) HHVM tests pass now (disregarding that stupid Point bug)

**Comment by afk11** [comment]
Thanks, nice to have HHVM working now. Is the gmp_rand bug gone because they've fixed it upstream? or that we've stopped using that?

**Comment by aztech-dev** [comment]
We stopped using it. It was only used by the RNG, which was replaced by the
new RNG classes (mcrypt/urandom and your hmac implementation)

**Comment by afk11** [comment]
Ah ok. Amazing it hasn't been added to HHVM yet! I'll merge #10 now, everything's back working besides the point failure

**Comment by aztech-dev** [comment]
Yup, well it doesn't really matter anymore. I rebased with your latest commits so this is ready for merge

**Pull request merged**
