### PR TITLE
Refactor random

### PR DESCRIPTION
**Pull request by afk11**
Refactor Bitcoin\Crypto\Random class:

 - Create Bitcoin\Crypto\Random namespace
 - Add RBGInterface
 - HMACDRBG, RFC6979 and Random are now tested and extend RBGInterface
 - Removed KProvider namespace & classes, all implementations are in Bitcoin\Crypto\Random
 - Signer takes an RBGInterface of indiscriminate type.

### CODE REVIEW

**Comment by btcdrak** [comment]
I think your namespace should begin with `Afk11\`

**Comment by aztech-dev** [comment]
RBG = RandomByteGenerator ?

**Comment by btcdrak** [comment]
Also you should camel case.

**Comment by afk11** [comment]
Re namespace, cool yeah ruben suggested the same. Did I miss one on the camel casing? or did you and Thibaud post at the same time.. 

@aztech-dev Random Byte Generator.. But will rename those now.

**Comment by aztech-dev** [comment]
The failing test is my fault (see https://github.com/mdanter/phpecc/pull/66), you don't need to do anything on this lib to fix it

**Comment by btcdrak** [comment]
Yeah, there are some things like `RBGInterface` which should be `RbgInterface`

**Comment by afk11** [comment]
Cool, I'll run over it in a bit just stepping out for a few!

**Comment by afk11** [comment]
Ok, moved everything to a vendor namespace, and addressed most of the capitalized class names. A couple of tests for the script interpreter as well..

**Pull request merged**
